[project]
name = "mock-lite"
version = "0.0.1"
description = "Mock project for ai_onboard lite testing"
requires-python = ">=3.8"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
