name: CI

on:
  push:
    branches:
      - main
      - develop
      - "feature/**"
      - "feat/**"
      - "bugfix/**"
      - "hotfix/**"
      - "release/**"
      - "fix/**"
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[dev]
      - name: Black
        run: black --check .
      - name: isort
        run: isort --check-only .
      - name: Flake8
        run: flake8 .

  typecheck:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[dev]
      - name: MyPy
        run: mypy --python-version 3.8 ai_onboard

  tests:
    name: Unit & Integration Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[test]
      - name: Run pytest (fast suite)
        run: pytest -m "not performance" --maxfail=1 --disable-warnings

  security:
    name: Security & Dependency Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[prod]
          python -m pip install pip-audit
      - name: Bandit
        run: bandit -r ai_onboard -ll
      - name: Safety
        run: safety check --full-report || true
      - name: pip-audit
        run: pip-audit || true
