name: ci

on: [pull_request, push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v5
        with: { python-version: "3.8" }
      - run: python -m pip install --upgrade pip
      - run: pip install pytest pyyaml
      - name: Install ai-onboard package
        run: pip install -e .
      - name: Protected paths
        shell: pwsh
        run: python scripts/protected_paths_diff.py origin/${{ github.base_ref || 'main' }}
      - name: Smoke summary
        shell: pwsh
        run: python -m ai_onboard prompt summary --level brief | Out-File -FilePath aiob_summary.json
      - uses: actions/upload-artifact@v4
        with: { name: aiob_summary, path: aiob_summary.json }
      - name: Tests
        run: pytest

